
from django.conf.urls import patterns, include, url

from yoolotto.second_chance.views import *

urlpatterns = patterns('',
    url('^wallet/(?P<filter>.+)$', AdCoupons.as_view()),    
    url('^vendor', Advertisors.as_view()),
    url('^faq', FrequentQuestions.as_view()),
    url('^appthis_history', AppThisTransactionHistory.as_view()),
    url('^commercial_video_rewards', CommercialVideoRewardsInfo.as_view()),
    url('^yoo_commercial_rewards', CommercialVideoRewardsInfo.as_view()),
    url('^commyupo_hsdkhdfkj_vdo_bnnr_addmndsuw1', CommercialVideoRewardsInfo.as_view()),
    url('^kiip_details', KiipDetails.as_view()),
    url('^daily_checkin_reward',DailyCheckInReward.as_view()),
    url('^appromoters_android_package_details', AppromotersAndroidPackageDetails.as_view()),
    url('^appromoters_android_offers_installed_details', AppromotersAndroidInstalledOfferDetails.as_view()),
    url('^postback', AppThisPostback.as_view()),
    url('^appthis_faq',AppThisFrequentQuestions.as_view()),
    url('^appthis_instructions_faq',AppThisInstructionsFAQ.as_view()),
    url('^appthis_offer_details',AppThisOfferDetails.as_view()),
    url('^android_package_details', AppThisAndroidPackageDetails.as_view()),
    url('^android_offers_installed_details', AppThisAndroidInstalledOfferDetails.as_view()),
    url('^appromoter_offer_installation_details', AppromoterInstalledDetails.as_view()),
    url('^appromoter_param_values', AppromoterParametersValues.as_view()),
    url('^AdToApp_coins', AddToAppDetails.as_view()),
    url('^redeem_ad', AdRedeem.as_view()),
    url('^coins_reduction', CoinsReduction.as_view()),
    url('^ltv',LifeTimeValueStatus.as_view()),
    url('^get_offer_ids',LifeTimeValueOfferId.as_view()),
    url('^timer_ad', TimerAd.as_view()),
    url('^invitation', InviteFriends.as_view()),
    url('^android_game', AndroidGame.as_view()),
    url('^android_numbers', AndroidNumbers.as_view()),
    #url('^add_refering_coins',CoinsTracking.as_view()),
    url('^add_coins', AddCoins.as_view()),
    url('^ad_colony',AdColony.as_view()),
    url('^screen_ads', ScreenAds.as_view()),
    url('^transaction_history',TransactionHistory.as_view()),
    url('^giftcard_cashout',GiftCardCashout.as_view()),
    url('^yoo_giftcard',GiftCardCashout.as_view()),
    url('^time_cal', TimeCal.as_view()),
    url('^social_message',SocialMessage.as_view()),
    url('^sca',SCA_url.as_view()),
    url('^dwolla_details',Dwolla.as_view()),
    url('^yoo_cashout',Dwolla.as_view()),
    url('^event_tracking',EventTracking.as_view()),
    url('^event_coins',CoinsAdditionReferral.as_view()),
    url('^fantasy_faq',FantasyFrequentQuestions.as_view()),
    url('^dwolla_faq',DwollaFrequentQuestions.as_view()),
   # url('^det',Det_Data.as_view()),
    #url('^yoocoins_info,')
    url('^in_app_fuel_callback/(?P<userID>.+)/(?P<currency>.+)/(?P<game_id>.+)/(?P<sig>.+)$',InAppFuelCallback.as_view()),
)
